# Company Information
company_name: Adassa FinTech
domain_name: fintech.adassa.com.jm
address_line: Kingston
country: Jamaica
company_email: mail@adassa.com.jm
description: This is the Adassa FinTech website.
meta_description: financial management system, information technology, personal finance

# Site Information
title: Adassa FinTech
author: Desmond Bennett
baseurl: ""
url: https://fintech.adassa.com.jm
permalink: pretty

# Social Links
facebook_link: https://www.facebook.com/desmondpbennett
twitter_link: https://twitter.com/DPB_and_A
github_link: https://github.com/Adassa-Enterprise-Solutions/

disqus: false
disqus_shortname: adassa_fintech

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate-v2

jekyll_admin:
  hidden_links:
    - configuration
  homepage: "pages"  
  
